# Generated by Django 5.0.6 on 2026-06-08 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('laptop', 'Laptop'), ('mobile', 'Mobile'), ('software', 'Software'), ('furniture', 'Furniture'), ('vehicle', 'Vehicle'), ('other', 'Other')], default='other', max_length=20)),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='new', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_maintenance', 'In Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('condition_on_return', models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assets.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_out_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_type', models.CharField(choices=[('warranty', 'Warranty'), ('license', 'License'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('alert_sent', models.BooleanField(default=False)),
                ('days_before_alert', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiries', to='assets.asset')),
            ],
            options={
                'ordering': ['expiry_date'],
                'unique_together': {('asset', 'expiry_type')},
            },
        ),
    ]
